### ISSUE TITLE
import amp_tdm_loader error

### ISSUE THREAD

**Issue by changyunke** [ZhouYuxuanYX/Unsupervised-Deep-Learning-Framework-for-Anomaly-Detection-in-Time-Series-#2]
import amp_tdm_loader is error in my environment with ubuntu1604. when i replace amp_tdm_loader with tdm_loader, there are some errors,as follows:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tdm_loader\tdm_loader.py", line 264, in get_column_index
    ext_id = self._root.findall(".//double_sequence/[@id='" + str(data_usi) + "']/values")[0].get('external')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tdm_loader\tdm_loader.py", line 266, in get_column_index
    ext_id = self._root.findall(".//long_sequence/[@id='" + str(data_usi) + "']/values")[0].get(
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pycharm/Unsupervised-Deep-Learning-Framework-for-Anomaly-Detection-in-Time-Series--master/import_data.py", line 37, in <module>
    open_data(data_path,lst)
  File "D:/pycharm/Unsupervised-Deep-Learning-Framework-for-Anomaly-Detection-in-Time-Series--master/import_data.py", line 28, in open_data
    data_list[index].append(file[channels[index]])
  File "D:\Anaconda3\lib\site-packages\tdm_loader\tdm_loader.py", line 533, in __getitem__
    return self.channel(channel_group, channel)
  File "D:\Anaconda3\lib\site-packages\tdm_loader\tdm_loader.py", line 347, in channel
    ch_number = self.get_column_index(channel_group, channel, occurrence=ch_occurrence)
  File "D:\Anaconda3\lib\site-packages\tdm_loader\tdm_loader.py", line 271, in get_column_index
    " or Channel " + str(channel) + " not found")
IndexError: Channel group 0 or Channel 3 not found

how can i solve it?
thank you!

**Comment by ZhouYuxuanYX** [comment]
Hi:

Sorry for the late response!

The amp_tdm_loader is actually a modified version of the tdm_loader for our internal use only and I have just forgotten to remove this part.

I would recommend you to try out this framework on the NAB dataset instead using the NAB dataset.py file. If you want to use this on TDM file, then you have to write read_data function yourself.
